// packages/quickpage/template/vue/App.vue
<template>
  <img alt="Vue logo" src="./assets/logo.png" />
  <HelloWorld msg="Hello Vue 3 + Vite" />
</template>

<script setup>
import HelloWorld from './components/HelloWorld.vue'
// This starter template is using Vue 3 experimental <script setup> SFCs
// Check out https://github.com/vuejs/rfcs/blob/script-setup-2/active-rfcs/0000-script-setup.md
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// packages/quickpage/template/svelte/App.svelte
<script>
    import logo from './assets/svelte.png'
    import Counter from './Counter.svelte'
  </script>
  
  <main>
    <img src={logo} alt="Svelte Logo" />
    <h1>Hello world!</h1>
  
    <Counter />
  
    <p>
      Visit <a href="https://svelte.dev">svelte.dev</a> to learn how to build Svelte
      apps.
    </p>
  
    <p>
      Check out <a href="https://github.com/sveltejs/kit#readme">SvelteKit</a> for
      the officially supported framework, also powered by Vite!
    </p>
  </main>
  
  <style>
    :root {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen,
        Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
    }
    main {
      text-align: center;
      padding: 1em;
      margin: 0 auto;
    }
    img {
      height: 16rem;
      width: 16rem;
    }
    h1 {
      color: #ff3e00;
      text-transform: uppercase;
      font-size: 4rem;
      font-weight: 100;
      line-height: 1.1;
      margin: 2rem auto;
      max-width: 14rem;
    }
    p {
      max-width: 14rem;
      margin: 1rem auto;
      line-height: 1.35;
    }
    @media (min-width: 480px) {
      h1 {
        max-width: none;
      }
      p {
        max-width: none;
      }
    }
  </style>
